# coding: utf-8

"""
    CrawlSnap API

    CrawlSnap is a data intelligence platform. It delivers structured, on-demand data through fast, typed HTTP APIs you can call from any language. This reference covers authentication, the response envelope, error handling, and the available CrawlSnap data products:    - **VectorSnap** — reputation, detections, categories, and relationships     for url / hash / ip / domain.   - **PulseSnap** — threat-intelligence pulse (and sandbox) enrichment for     url / hash / ip / domain.   - **SubdoSnap** — paginated subdomain enumeration for a domain.  ## Authentication  Authenticate every request with your CrawlSnap API key, sent as a Bearer token in the `Authorization` header:      Authorization: Bearer sk-cs-...  Create and rotate keys from your dashboard. Treat the key like a password: it carries your full quota and must stay secret. Never embed it in client-side code or commit it to source control.  ## Response envelope  Every response — success or error — uses the same envelope:  ```json {   \"data\": { ... },          // payload on success, null on failure   \"is_success\": true,        // authoritative success flag   \"message\": \"Success\",     // human-readable summary   \"response_code\": 200       // mirrors the HTTP status code } ```  Always check `is_success` before reading `data`.  ## Status codes  HTTP status codes follow standard REST semantics; the body `response_code` mirrors the HTTP status.    - **200** — success, `data` populated.   - **400** — invalid input (malformed URL / hash / IP / domain).   - **401** — missing or invalid API key.   - **402** — out of credits, or monthly quota exceeded.   - **403** — subscription is not active.   - **404** — no IoC data found for the supplied indicator.   - **429** — daily request limit exceeded.   - **5xx** — server error, or the upstream enrichment service was     unavailable / timed out. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@crawlsnap.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IocHashScanData(BaseModel):
    """
    IocHashScanData
    """ # noqa: E501
    hash_id: StrictStr = Field(description="SHA-256 of the queried hash (resolved upstream when md5/sha1 supplied).")
    search_type: StrictStr
    ssdeep: Optional[StrictStr] = None
    type_tag: Optional[StrictStr] = None
    type_tags: Optional[List[StrictStr]] = None
    magic: Optional[StrictStr] = None
    magika: Optional[StrictStr] = None
    type_description: Optional[StrictStr] = None
    meaningful_name: Optional[StrictStr] = None
    authentihash: Optional[StrictStr] = None
    detectiteasy: Optional[Dict[str, Any]] = None
    trid: Optional[List[Dict[str, Any]]] = None
    type_extension: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    tlsh: Optional[StrictStr] = None
    analysis_date: Optional[StrictInt] = None
    modification_date: Optional[StrictInt] = None
    md5: Optional[StrictStr] = None
    sha1: Optional[StrictStr] = None
    sha256: Optional[StrictStr] = None
    file_size: Optional[StrictInt] = None
    dropped_files: Optional[List[Dict[str, Any]]] = None
    bundled_files: Optional[List[Dict[str, Any]]] = None
    contacted_ips: Optional[List[Dict[str, Any]]] = None
    contacted_domains: Optional[List[Dict[str, Any]]] = None
    sigma: Optional[Dict[str, Any]] = None
    sigma_stats: Optional[Dict[str, Any]] = None
    classification: Optional[Dict[str, Any]] = None
    pe_info: Optional[Dict[str, Any]] = None
    signature: Optional[Dict[str, Any]] = None
    votes_result: Optional[Dict[str, Any]] = None
    sandbox_verdicts: Optional[Dict[str, Any]] = None
    security_vendor_analysis: Optional[Dict[str, Any]] = None
    security_vendor_analysis_stats: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["hash_id", "search_type", "ssdeep", "type_tag", "type_tags", "magic", "magika", "type_description", "meaningful_name", "authentihash", "detectiteasy", "trid", "type_extension", "tags", "tlsh", "analysis_date", "modification_date", "md5", "sha1", "sha256", "file_size", "dropped_files", "bundled_files", "contacted_ips", "contacted_domains", "sigma", "sigma_stats", "classification", "pe_info", "signature", "votes_result", "sandbox_verdicts", "security_vendor_analysis", "security_vendor_analysis_stats"]

    @field_validator('search_type')
    def search_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['hash']):
            raise ValueError("must be one of enum values ('hash')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IocHashScanData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IocHashScanData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "hash_id": obj.get("hash_id"),
            "search_type": obj.get("search_type"),
            "ssdeep": obj.get("ssdeep"),
            "type_tag": obj.get("type_tag"),
            "type_tags": obj.get("type_tags"),
            "magic": obj.get("magic"),
            "magika": obj.get("magika"),
            "type_description": obj.get("type_description"),
            "meaningful_name": obj.get("meaningful_name"),
            "authentihash": obj.get("authentihash"),
            "detectiteasy": obj.get("detectiteasy"),
            "trid": obj.get("trid"),
            "type_extension": obj.get("type_extension"),
            "tags": obj.get("tags"),
            "tlsh": obj.get("tlsh"),
            "analysis_date": obj.get("analysis_date"),
            "modification_date": obj.get("modification_date"),
            "md5": obj.get("md5"),
            "sha1": obj.get("sha1"),
            "sha256": obj.get("sha256"),
            "file_size": obj.get("file_size"),
            "dropped_files": obj.get("dropped_files"),
            "bundled_files": obj.get("bundled_files"),
            "contacted_ips": obj.get("contacted_ips"),
            "contacted_domains": obj.get("contacted_domains"),
            "sigma": obj.get("sigma"),
            "sigma_stats": obj.get("sigma_stats"),
            "classification": obj.get("classification"),
            "pe_info": obj.get("pe_info"),
            "signature": obj.get("signature"),
            "votes_result": obj.get("votes_result"),
            "sandbox_verdicts": obj.get("sandbox_verdicts"),
            "security_vendor_analysis": obj.get("security_vendor_analysis"),
            "security_vendor_analysis_stats": obj.get("security_vendor_analysis_stats")
        })
        return _obj


