# coding: utf-8

"""
    CrawlSnap API

    CrawlSnap is a data intelligence platform. It delivers structured, on-demand data through fast, typed HTTP APIs you can call from any language. This reference covers authentication, the response envelope, error handling, and the available CrawlSnap data products:    - **VectorSnap** — reputation, detections, categories, and relationships     for url / hash / ip / domain.   - **PulseSnap** — threat-intelligence pulse (and sandbox) enrichment for     url / hash / ip / domain.   - **SubdoSnap** — paginated subdomain enumeration for a domain.  ## Authentication  Authenticate every request with your CrawlSnap API key, sent as a Bearer token in the `Authorization` header:      Authorization: Bearer sk-cs-...  Create and rotate keys from your dashboard. Treat the key like a password: it carries your full quota and must stay secret. Never embed it in client-side code or commit it to source control.  ## Response envelope  Every response — success or error — uses the same envelope:  ```json {   \"data\": { ... },          // payload on success, null on failure   \"is_success\": true,        // authoritative success flag   \"message\": \"Success\",     // human-readable summary   \"response_code\": 200       // mirrors the HTTP status code } ```  Always check `is_success` before reading `data`.  ## Status codes  HTTP status codes follow standard REST semantics; the body `response_code` mirrors the HTTP status.    - **200** — success, `data` populated.   - **400** — invalid input (malformed URL / hash / IP / domain).   - **401** — missing or invalid API key.   - **402** — out of credits, or monthly quota exceeded.   - **403** — subscription is not active.   - **404** — no IoC data found for the supplied indicator.   - **429** — daily request limit exceeded.   - **5xx** — server error, or the upstream enrichment service was     unavailable / timed out. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@crawlsnap.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IocDomainScanData(BaseModel):
    """
    IocDomainScanData
    """ # noqa: E501
    hash_id: StrictStr
    search_type: StrictStr
    domain: Optional[StrictStr] = None
    reputation: Optional[StrictInt] = None
    tags: Optional[List[StrictStr]] = None
    whois: Optional[StrictStr] = None
    whois_update_date: Optional[StrictInt] = None
    modification_date: Optional[StrictInt] = None
    tld: Optional[StrictStr] = None
    dns_records_update_date: Optional[StrictInt] = None
    http_certificate_update_date: Optional[StrictInt] = None
    jarm: Optional[StrictStr] = None
    registrar: Optional[StrictStr] = None
    analysis_date: Optional[StrictInt] = None
    votes_result: Optional[Any] = Field(default=None, description="Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.")
    security_vendor_analysis: Optional[Any] = Field(default=None, description="Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.")
    security_vendor_analysis_stats: Optional[Any] = Field(default=None, description="Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.")
    categories: Optional[Any] = Field(default=None, description="Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.")
    popularity_ranks: Optional[Any] = Field(default=None, description="Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.")
    dns_records: Optional[List[Dict[str, Any]]] = None
    http_certificate: Optional[Any] = Field(default=None, description="Opaque upstream pass-through; shape varies (object/array/scalar), so it is typed as free-form.")
    referrer_files: Optional[List[Dict[str, Any]]] = Field(default=None, alias="referrerFiles")
    communicating_files: Optional[List[Dict[str, Any]]] = None
    subdomains: Optional[List[Dict[str, Any]]] = None
    resolutions: Optional[List[Dict[str, Any]]] = None
    siblings: Optional[List[Dict[str, Any]]] = None
    __properties: ClassVar[List[str]] = ["hash_id", "search_type", "domain", "reputation", "tags", "whois", "whois_update_date", "modification_date", "tld", "dns_records_update_date", "http_certificate_update_date", "jarm", "registrar", "analysis_date", "votes_result", "security_vendor_analysis", "security_vendor_analysis_stats", "categories", "popularity_ranks", "dns_records", "http_certificate", "referrerFiles", "communicating_files", "subdomains", "resolutions", "siblings"]

    @field_validator('search_type')
    def search_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['domain']):
            raise ValueError("must be one of enum values ('domain')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IocDomainScanData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if votes_result (nullable) is None
        # and model_fields_set contains the field
        if self.votes_result is None and "votes_result" in self.model_fields_set:
            _dict['votes_result'] = None

        # set to None if security_vendor_analysis (nullable) is None
        # and model_fields_set contains the field
        if self.security_vendor_analysis is None and "security_vendor_analysis" in self.model_fields_set:
            _dict['security_vendor_analysis'] = None

        # set to None if security_vendor_analysis_stats (nullable) is None
        # and model_fields_set contains the field
        if self.security_vendor_analysis_stats is None and "security_vendor_analysis_stats" in self.model_fields_set:
            _dict['security_vendor_analysis_stats'] = None

        # set to None if categories (nullable) is None
        # and model_fields_set contains the field
        if self.categories is None and "categories" in self.model_fields_set:
            _dict['categories'] = None

        # set to None if popularity_ranks (nullable) is None
        # and model_fields_set contains the field
        if self.popularity_ranks is None and "popularity_ranks" in self.model_fields_set:
            _dict['popularity_ranks'] = None

        # set to None if http_certificate (nullable) is None
        # and model_fields_set contains the field
        if self.http_certificate is None and "http_certificate" in self.model_fields_set:
            _dict['http_certificate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IocDomainScanData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "hash_id": obj.get("hash_id"),
            "search_type": obj.get("search_type"),
            "domain": obj.get("domain"),
            "reputation": obj.get("reputation"),
            "tags": obj.get("tags"),
            "whois": obj.get("whois"),
            "whois_update_date": obj.get("whois_update_date"),
            "modification_date": obj.get("modification_date"),
            "tld": obj.get("tld"),
            "dns_records_update_date": obj.get("dns_records_update_date"),
            "http_certificate_update_date": obj.get("http_certificate_update_date"),
            "jarm": obj.get("jarm"),
            "registrar": obj.get("registrar"),
            "analysis_date": obj.get("analysis_date"),
            "votes_result": obj.get("votes_result"),
            "security_vendor_analysis": obj.get("security_vendor_analysis"),
            "security_vendor_analysis_stats": obj.get("security_vendor_analysis_stats"),
            "categories": obj.get("categories"),
            "popularity_ranks": obj.get("popularity_ranks"),
            "dns_records": obj.get("dns_records"),
            "http_certificate": obj.get("http_certificate"),
            "referrerFiles": obj.get("referrerFiles"),
            "communicating_files": obj.get("communicating_files"),
            "subdomains": obj.get("subdomains"),
            "resolutions": obj.get("resolutions"),
            "siblings": obj.get("siblings")
        })
        return _obj


