# coding: utf-8

"""
    CrawlSnap API

    The CrawlSnap API provides on-demand threat-intelligence enrichment for indicators of compromise (IoCs). Submit a URL, file hash, IPv4 address, or domain and receive structured enrichment from multiple upstream sources:    - **vector-scan** — VirusTotal-derived reputation, detections, and     relationships for url / hash / ip / domain.   - **pulse-snap** — AlienVault OTX pulse (and sandbox) enrichment for     url / hash / ip / domain.   - **subdo-snap** — paginated subdomain enumeration for a domain.  ## Authentication  Authenticate every request with your CrawlSnap API key, sent as a Bearer token in the `Authorization` header:      Authorization: Bearer sk-cs-...  Create and rotate keys from your dashboard. Treat the key like a password: it carries your full quota and must stay secret. Never embed it in client-side code or commit it to source control.  ## Response envelope  Every response — success or error — uses the same envelope:  ```json {   \"data\": { ... },          // payload on success, null on failure   \"is_success\": true,        // authoritative success flag   \"message\": \"Success\",     // human-readable summary   \"response_code\": 200       // mirrors the HTTP status code } ```  Always check `is_success` before reading `data`.  ## Status codes  HTTP status codes follow standard REST semantics; the body `response_code` mirrors the HTTP status.    - **200** — success, `data` populated.   - **400** — invalid input (malformed URL / hash / IP / domain).   - **401** — missing or invalid API key.   - **402** — out of credits, or monthly quota exceeded.   - **403** — subscription is not active.   - **404** — no IoC data found for the supplied indicator.   - **429** — daily request limit exceeded.   - **5xx** — server error, or the upstream enrichment service was     unavailable / timed out. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@crawlsnap.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from crawlsnap.models.ioc_hash_scan_data import IocHashScanData

class TestIocHashScanData(unittest.TestCase):
    """IocHashScanData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IocHashScanData:
        """Test IocHashScanData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IocHashScanData`
        """
        model = IocHashScanData()
        if include_optional:
            return IocHashScanData(
                hash_id = '',
                search_type = 'hash',
                ssdeep = '',
                type_tag = '',
                type_tags = [
                    ''
                    ],
                magic = '',
                magika = '',
                type_description = '',
                meaningful_name = '',
                authentihash = '',
                detectiteasy = { },
                trid = [
                    { }
                    ],
                type_extension = '',
                tags = [
                    ''
                    ],
                tlsh = '',
                analysis_date = 56,
                modification_date = 56,
                md5 = '',
                sha1 = '',
                sha256 = '',
                file_size = 56,
                dropped_files = [
                    { }
                    ],
                bundled_files = [
                    { }
                    ],
                contacted_ips = [
                    { }
                    ],
                contacted_domains = [
                    { }
                    ],
                sigma = { },
                sigma_stats = { },
                classification = { },
                pe_info = { },
                signature = { },
                votes_result = { },
                sandbox_verdicts = { },
                security_vendor_analysis = { },
                security_vendor_analysis_stats = { }
            )
        else:
            return IocHashScanData(
                hash_id = '',
                search_type = 'hash',
        )
        """

    def testIocHashScanData(self):
        """Test IocHashScanData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
