# coding: utf-8

# flake8: noqa

"""
    CrawlSnap API

    The CrawlSnap API provides on-demand threat-intelligence enrichment for indicators of compromise (IoCs). Submit a URL, file hash, IPv4 address, or domain and receive structured enrichment from multiple upstream sources:    - **vector-scan** — VirusTotal-derived reputation, detections, and     relationships for url / hash / ip / domain.   - **pulse-snap** — AlienVault OTX pulse (and sandbox) enrichment for     url / hash / ip / domain.   - **subdo-snap** — paginated subdomain enumeration for a domain.  ## Authentication  Authenticate every request with your CrawlSnap API key, sent as a Bearer token in the `Authorization` header:      Authorization: Bearer sk-cs-...  Create and rotate keys from your dashboard. Treat the key like a password: it carries your full quota and must stay secret. Never embed it in client-side code or commit it to source control.  ## Response envelope  Every response — success or error — uses the same envelope:  ```json {   \"data\": { ... },          // payload on success, null on failure   \"is_success\": true,        // authoritative success flag   \"message\": \"Success\",     // human-readable summary   \"response_code\": 200       // mirrors the HTTP status code } ```  Always check `is_success` before reading `data`.  ## Status codes  HTTP status codes follow standard REST semantics; the body `response_code` mirrors the HTTP status.    - **200** — success, `data` populated.   - **400** — invalid input (malformed URL / hash / IP / domain).   - **401** — missing or invalid API key.   - **402** — out of credits, or monthly quota exceeded.   - **403** — subscription is not active.   - **404** — no IoC data found for the supplied indicator.   - **429** — daily request limit exceeded.   - **5xx** — server error, or the upstream enrichment service was     unavailable / timed out. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@crawlsnap.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "PulseSnapApi",
    "SubdoSnapApi",
    "VectorScanApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "BaseResponse",
    "ErrorResponse",
    "IocDomainScanData",
    "IocHashScanData",
    "IocIpScanData",
    "IocUrlScanData",
    "PulseDomainScanData",
    "PulseHashScanData",
    "PulseIpScanData",
    "PulseSnapDomainResponse",
    "PulseSnapHashResponse",
    "PulseSnapIpResponse",
    "PulseSnapUrlResponse",
    "PulseUrlScanData",
    "SubdoSnapScanData",
    "SubdoSnapScanResponse",
    "VectorScanDomainResponse",
    "VectorScanHashResponse",
    "VectorScanIpResponse",
    "VectorScanUrlResponse",
]

# import apis into sdk package
from crawlsnap.api.pulse_snap_api import PulseSnapApi as PulseSnapApi
from crawlsnap.api.subdo_snap_api import SubdoSnapApi as SubdoSnapApi
from crawlsnap.api.vector_scan_api import VectorScanApi as VectorScanApi

# import ApiClient
from crawlsnap.api_response import ApiResponse as ApiResponse
from crawlsnap.api_client import ApiClient as ApiClient
from crawlsnap.configuration import Configuration as Configuration
from crawlsnap.exceptions import OpenApiException as OpenApiException
from crawlsnap.exceptions import ApiTypeError as ApiTypeError
from crawlsnap.exceptions import ApiValueError as ApiValueError
from crawlsnap.exceptions import ApiKeyError as ApiKeyError
from crawlsnap.exceptions import ApiAttributeError as ApiAttributeError
from crawlsnap.exceptions import ApiException as ApiException

# import models into sdk package
from crawlsnap.models.base_response import BaseResponse as BaseResponse
from crawlsnap.models.error_response import ErrorResponse as ErrorResponse
from crawlsnap.models.ioc_domain_scan_data import IocDomainScanData as IocDomainScanData
from crawlsnap.models.ioc_hash_scan_data import IocHashScanData as IocHashScanData
from crawlsnap.models.ioc_ip_scan_data import IocIpScanData as IocIpScanData
from crawlsnap.models.ioc_url_scan_data import IocUrlScanData as IocUrlScanData
from crawlsnap.models.pulse_domain_scan_data import PulseDomainScanData as PulseDomainScanData
from crawlsnap.models.pulse_hash_scan_data import PulseHashScanData as PulseHashScanData
from crawlsnap.models.pulse_ip_scan_data import PulseIpScanData as PulseIpScanData
from crawlsnap.models.pulse_snap_domain_response import PulseSnapDomainResponse as PulseSnapDomainResponse
from crawlsnap.models.pulse_snap_hash_response import PulseSnapHashResponse as PulseSnapHashResponse
from crawlsnap.models.pulse_snap_ip_response import PulseSnapIpResponse as PulseSnapIpResponse
from crawlsnap.models.pulse_snap_url_response import PulseSnapUrlResponse as PulseSnapUrlResponse
from crawlsnap.models.pulse_url_scan_data import PulseUrlScanData as PulseUrlScanData
from crawlsnap.models.subdo_snap_scan_data import SubdoSnapScanData as SubdoSnapScanData
from crawlsnap.models.subdo_snap_scan_response import SubdoSnapScanResponse as SubdoSnapScanResponse
from crawlsnap.models.vector_scan_domain_response import VectorScanDomainResponse as VectorScanDomainResponse
from crawlsnap.models.vector_scan_hash_response import VectorScanHashResponse as VectorScanHashResponse
from crawlsnap.models.vector_scan_ip_response import VectorScanIpResponse as VectorScanIpResponse
from crawlsnap.models.vector_scan_url_response import VectorScanUrlResponse as VectorScanUrlResponse

